### ISSUE TITLE
为特定的文件提供专有 ”编辑/查看“ 方式

### ISSUE THREAD

**Issue by Bkm016** [SacredCraft/Valhalla#1]
<img width="555" alt="image" src="https://github.com/SacredCraft/Valhalla/assets/27818531/5ebb4f1f-f636-4aca-8835-e5038ed2cbeb">

例如图片不可编辑，点击快速预览。
其他无模板文件点击以 Raw 模式编辑。

**Comment by LioRael** [comment]
完成于 #12
