### ISSUE TITLE
移除文件名格式化

### ISSUE THREAD

**Issue by Bkm016** [SacredCraft/Valhalla#10]
<img width="582" alt="image" src="https://github.com/SacredCraft/Valhalla/assets/27818531/dd0b05eb-3db2-412b-bc85-0a5bd7ba4aae">

Editor/Files 后面的所有文件名以实际名称为准。

**Comment by LioRael** [comment]
完成于 [#d83979108c4d986cedb3b6a7855dd8bb9d9fe626](https://github.com/SacredCraft/Valhalla/commit/d83979108c4d986cedb3b6a7855dd8bb9d9fe626)
