### ISSUE TITLE
上传优化

### ISSUE THREAD

**Issue by Bkm016** [SacredCraft/Valhalla#23]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/8b2285d1-2257-433d-912e-ee9e3e3c71cd">

现在上传文件只有最终提示，没有过程。

<img width="385" alt="image" src="https://github.com/user-attachments/assets/409e6e45-eb1c-4ac2-866f-6b97404be5de">

假设上传 2 个总共 10 MB 的文件，中途没有任何反馈。

**Comment by Bkm016** [comment]
如果是多个文件，可以把提示拆开。

**Comment by LioRael** [comment]
已完成
