### ISSUE TITLE
Tab 优化

### ISSUE THREAD

**Issue by Bkm016** [SacredCraft/Valhalla#28]
# 1 希望可以增加一个右键菜单，包含的功能类似于：
![image](https://github.com/user-attachments/assets/03338a16-d2fd-451b-bb7d-078b212df230)
1. 关闭所有
2. 关闭其他
3. 关闭上面的
4. 关闭下面的

# 2 移除 Tab 进入动画
![image](https://github.com/user-attachments/assets/2ef1779f-f76a-4375-83bf-45a196a557fd)
就是从下往上滑入的这个效果，体验不好。这动画还是概率触发的，进入文件夹也会出现。

**Comment by LioRael** [comment]
已完成
