### ISSUE TITLE
文件命名漏洞

### ISSUE THREAD

**Issue by Nipuru** [SacredCraft/Valhalla#31]
文件命名存在漏洞
例如使用 ../ 或绝对路径，可以使文件转移到 Path 目录之外，

受影响的功能：
1. 文件上传命名
2. 文件移动或重命名

解决方法：
1. 判断文件的父文件夹是否包含 Path 目录

另外文件删除功能是否有此风险

**Comment by LioRael** [comment]
如果前端被 hack, 文件删除功能确实存在此风险

**Comment by LioRael** [comment]
存在该类风险的操作同样包括:复制文件、写入文件等

**Comment by LioRael** [comment]
目前已完成对上述所有操作的路径安全性检测 #39

**Comment by Bkm016** [comment]
那么吊？
