### ISSUE TITLE
文件上传删除按钮异常

### ISSUE THREAD

**Issue by Nipuru** [SacredCraft/Valhalla#33]
文件上传列表，当文件名过长时，删除按钮会消失

![69dc69d0d86232923b83e1f8ba81f240](https://github.com/user-attachments/assets/a6ba718c-b444-43ac-813c-b37dc441c81c)

**Comment by LioRael** [comment]
<img width="411" alt="image" src="https://github.com/user-attachments/assets/4262f1b6-f8fe-4f9f-80ea-3425a8bdc3a6">

完成于 #37
